### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by jbicha** [shimmerproject/Greybird#130]
...with a version number higher than 2.1.2.

Ubuntu has packaged Greybird as `greybird-gtk-theme` in the [shimmer themes](https://launchpad.net/ubuntu/+source/shimmer-themes/) source packge, but the version number they have been picking seems arbitrary. I'd like to have the version number in Ubuntu match the upstream version number, but Ubuntu's version is already 2.1.2.

**Comment by ochosi** [comment]
I think the problem is that the shimmer-themes package doesn't follow the version numbers of a single theme but has its own scheme (as it used to include several themes).

I would say the best workaround would be to have Greybird as a separate package. What I can do though is do a "3.18" release, I've been wanting to get in sync with Gtk3 version numbers for a while (as that seems to be the main reference of the theme anyway).

**Comment by jbicha** [comment]
Yes, 3.18 is a good number. It matches what [mate-themes](https://github.com/mate-desktop/mate-themes/releases) does and I think it makes a lot of sense (or at least it did before you could have separate directories for different targeted GTK versions).

**Comment by jbicha** [comment]
Yes, I am working to split the themes into separate packages in Debian and Ubuntu. It should make it easier to track version numbers and bugs.

**Comment by bluesabre** [comment]
It makes sense to split Greybird out into its own package.  And I definitely +1 using GTK compatibility version as the release version.

**Comment by jbicha** [comment]
When I upload greybird-gtk-theme next to Ubuntu, it will have a version number something like
`2.1.2.is.1.6.2+20160629~gtk320~a00cb2c-1ubuntu1`
…which is kind of fun (but not the [longest](https://launchpad.net/ubuntu/+source/gnome-software/3.20.1+git20160617.1.0440874.ubuntu-xenial-0ubuntu1~16.04.1) either).

That's a git snapshot of the gtk320 branch (commit a00cb2c from June 29).

**Comment by ochosi** [comment]
@jbicha https://github.com/shimmerproject/Greybird/releases/tag/v3.18.0
