### ISSUE TITLE
xfce4-notifyd-config 0.3.0 theme has changed

### ISSUE THREAD

**Issue by jristz** [shimmerproject/Greybird#140]
for the new xfce4-notifyd-config 0.3.0 the theme has changed, now is a gtk3 app and therefor no one of the themes in the gtk3.20 are working (and in fact not show in the theme selections).

so now it need the greybird xfce4-notifyd themes to be ported too since the 0.3.0 is concidered stable to be shipped (and even arch has packaged it and now is on stable repos) AND will be in next version

**Comment by ochosi** [comment]
If you use the gtk3.20 branch you'll see that it supports xfce4-notifyd 0.3.0.
For the moment I'm not planning to do a maintenance release for Gtk3.18 only for the xfce4-notifyd 0.3.0 support.

Also see the docs I wrote a few days ago on the subject: http://docs.xfce.org/apps/notifyd/theming
In short: the main idea behind notifyd 0.3.0 is that the currently selected Gtk+ theme will be used by default (and it should be the most consistent default, because notifyd now uses the common classes "osd" and "app-notification").

**Comment by jristz** [comment]
Im using the 3.20 branch and today xfce4 notify 0.3.0 land and I update and
no one of the themes are showing on the notify theme

**Comment by ochosi** [comment]
Added back the standalone themes now (probably need to kill xfce4-notifyd before they show up and work).
