### ISSUE TITLE
Dark panels in MATE

### ISSUE THREAD

**Issue by mrnhmath** [shimmerproject/Greybird#202]
I think the theme should show dark panels instead of grey in MATE, as does Xfce.

**Comment by mark-mb** [comment]
I have the same issue, and I can give more information on it. I recently updated my distro, and MATE updated from version 1.14 to version 1.18. Because of this update, components such as MATE Panels use GTK 3 instead of GTK 2, as they were using before.

In order to have a dark panel in MATE with GTK 3, it would be necessary to have a "_mate.scss", similar to the "_xfce.scss" that Greybird has now.

Is there any plan to add this MATE extension in Greybird?

**Comment by ochosi** [comment]
Sorry, I'm not a Mate user so I don't actively support it. I'm happy to merge patches if somebody wants to maintain that part, but I'm not the right person for the task.

**Comment by ochosi** [comment]
So as I said, if someone else wants to add more support for Mate I'll be happy to merge, but I won't work on this myself. Feel free to re-open the issue in that case.
