### ISSUE TITLE
The ALT+TAB recycler wrongly selects an item even when a mouse is hovered over it.

### ISSUE THREAD

**Issue by prahladyeri** [shimmerproject/Greybird#231]
This issue is so apparent and so old that I'm surprised nobody has reported it yet, and it still occurs on Xubuntu 18.04. But maybe, some may not consider it a bug at all, but a design feature!

The problem is quite clear: As a power user, when I press "ALT+TAB", I want my keyboard to decide what the next selected window is. If the mouse cursor hovers over the cycler dialog at that exact moment, a random item which is under that cursor gets selected which wasn't my intention at all!

![ALT+TAB cycling incorrect](https://prahladyeri.com/wp-content/uploads/2018/09/alt-tab-cycling.png)
_ALT+TAB cycler dialog in Greybird theme._

Please read [my entire blog post about this issue](https://prahladyeri.com/blog/2018/09/performing-a-little-usability-tweak-on-the-xfce-window-recycler-in-greybird-theme.html) to understand it more fully, and also find a temporary workaround (a ~/.gtkrc-2.0 stylesheet).

**Comment by ochosi** [comment]
While the tabwin style has changed a bit since your version of Greybird (blue is now the keyboard highlight, grey is the mouse highlight) not styling the mouse hover is simply breaking a feature.

The mouse feature for tabwin is useful if you have the previews enabled and many open windows. People can also do that on Windows, OSX and even Gnome Shell (afaik) so this feature comes as no surprise.
Just not showing the highlight of the mouse hover would hide this feature and lead to confusion for those who accidentally click.

Most likely this should be addressed in Xfwm4 directly to not show the mouse hover unless the mouse moved *after* holding down alt-tab.
