### ISSUE TITLE
[Bug] Vertical panel with wrongly horizontal oriented elements

### ISSUE THREAD

**Issue by cabroncito** [shimmerproject/Greybird#244]
I stumbled upon this remarkable thing when setting up a new install of Xubuntu 18.04.2 on my tablet: When using *vertical* panels, the text (e.g. window names and clock) is not shown vertically as expected, but remains horizontal (similar to the desktop bar mode of the panel). When hovering over the clock or the window button, the text jumps to the correct vertical orientation. 

With a different theme for XFCE, text is always shown vertically as expected.

This bug I experienced was discussed quite a while ago in a different thread:
https://forum.xfce.org/viewtopic.php?pid=49971#p49971

**Comment by ochosi** [comment]
This is a known issue with the murrine Gtk2 engine, so the bug will be gone with Xfce Panel 4.13 (which you will find in newer releases of Xubuntu).

Unfortunately nothing I can do, the murrine engine also isn't maintained anymore...

(Other themes may not exhibit this bug because of using other engines or engine options.)

So unfortunately closed as wontfix (also invalid, because it's murrine's fault).
