### ISSUE TITLE
Sunken status bar in Thunar

### ISSUE THREAD

**Issue by bogomirov** [shimmerproject/Greybird#68]
I am using Greybird with XFCE on Debian Wheezy. In Thunar I get this sunken-edge status bar:

![thinar-screenshot](https://cloud.githubusercontent.com/assets/2456364/4372950/ae86a4fc-4328-11e4-8d32-43aceaf2a367.png)

Is this the appearance you have intended?

In Bluebird for example, the Thunar status bar looks smooth, and IMHO fits to the general outlook of the theme much better.

**Comment by ochosi** [comment]
Sorry for the late reply. The problem is that your thunar version is too old for this version of Greybird. The sidebar was restructured and there was some theme breakage related to it. Best try to check when the new thunar sidebar was released and then check the related Greybird code back in time. Unfortunately there's no way for me to fix the code to work in both Thunar versions.
